/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: losdayver (https://sketchfab.com/losdayver)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/ancient-portal-frame-934bbd85eb4041128a1fa4cde8ac0ea9
title: Ancient portal frame
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/portal.gltf')
  return (
    <group {...props}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1.6}>
        {/* <lineSegments geometry={nodes.Object_6.geometry} material={materials.mossy_bricks} /> */}
        {/* <mesh geometry={nodes.Object_2.geometry} material={materials.Fire} /> */}
        {/* <mesh geometry={nodes.Object_3.geometry} material={materials['Material.002']} /> */}
        {/* <mesh geometry={nodes.Object_4.geometry} material={materials.coal} /> */}
        {/* <mesh geometry={nodes.Object_5.geometry} material={materials.leather} /> */}
        <mesh geometry={nodes.Object_7.geometry} material={materials.portal2} />
        {/* <mesh geometry={nodes.Object_8.geometry} material={materials.wood} /> */}
        {/* <mesh geometry={nodes.Object_9.geometry} material={materials.frame_metal} /> */}
        {/* <mesh geometry={nodes.Object_10.geometry} material={materials.frame_metal} /> */}
        {/* <mesh geometry={nodes.Object_11.geometry} material={materials.frame_metal} /> */}
        {/* <mesh geometry={nodes.Object_12.geometry} material={materials['leaf.001']} /> */}
        {/* <mesh geometry={nodes.Object_13.geometry} material={materials.mossy_bricks} /> */}
        {/* <mesh geometry={nodes.Object_14.geometry} material={materials.torch_metal} />  */}
      </group>
    </group>
  )
}

useGLTF.preload('/portal.gltf')
